---
Metrics/LineLength:
  Max: 80
Metrics/ClassLength:
  Exclude:
    - test/**/test_*.rb
Naming/MemoizedInstanceVariableName:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.1
