---
Layout/LineLength:
  Max: 80
Metrics/ClassLength:
  Exclude:
    - test/**/test_*.rb
Gemspec/RequiredRubyVersion:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
